services:
  db:
    image: postgres:14.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-StudyConnect}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro # optional SQL scripts
    ports:
      - "5432:5432"
    networks:
      - appnetwork

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    networks:
      - appnetwork
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    container_name: keycloak
    command: -v start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER:-root}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-root}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    depends_on:
      - db
    networks:
      - appnetwork

  app:
    build: ./backend
    container_name: python_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - keycloak
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-StudyConnect}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL:-http://keycloak:8080}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-StudyConnectRealm}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-studyconnect-backend}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-test-secret-key}
      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID:-studyconnect-backend}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET:-test-secret-key}
    networks:
      - appnetwork
    profiles:
      - dev

  gatling:
    image: denvazh/gatling:latest
    container_name: gatling
    depends_on:
      - app
    networks:
      - appnetwork
    volumes:
      - ./gatling/simulations:/opt/gatling/user-files/simulations
      - ./gatling/resources:/opt/gatling/user-files/resources
      - ./gatling/results:/opt/gatling/results
    command: >
      -s ApiSimulation
    profiles:
      - test


volumes:
  db-data:
  pgadmin-data:

networks:
  appnetwork:
    driver: bridge